agents:
  queue: "{queue}"

label: "{name}"
key: "{slug}"

commands:
  - powershell -file qdb-code-signing\windows_package_sign.ps1
  - powershell -file scripts\teamcity\build_installer.ps1
  - powershell -file qdb-code-signing\windows_installer_sign.ps1


plugins:
  - bureau14/qdb-artifacts#master:
      download:
        projects:
          - project_id: "qdb-pkg-archives"
            files:
              - "*.zip"
            output-dir: .
          - project_id: "qdb-code-signing"
            clean: true
            files:
              - "qdb-code-signing.tar.gz"
            extract: true
            output-dir: qdb-code-signing
      upload:
        files:
        - "*.exe"
      promote: {}
